### ISSUE TITLE
Fix Compare release list

### ISSUE THREAD

**Issue by glaubervila** [linea-it/dri#1261]
@glaubervila UPDATE: 07/05/2024 - The solution to this issue now is to simply remove the compare button from the Sky viewer in order to comply with the LEGACY DES Science Server plan.

Error happens in Sky Viewer in the visiomatic view in the "Compare image" function, eventually the list of available releases brings an infinite list of repeated releases. making it impossible to use the function. a reload of the page is necessary for it to work correctly.

Steps to reproduce:
- Open Sky Viewer
- centralize the aladin on any tile.
- Switch to the "Visiomatic" view
- clicking the compare button, usually the error happens the first time the interface is opened.

**Comment by gschwend** [comment]
Added to milestone PH7 because it needs two releases for the comparison, but it might be obsolete if we decide to replace Visiomatic with Aladin in PH6. To be evaluated.

**Comment by glaubervila** [comment]
> Added to milestone PH7 because it needs two releases for the comparison, but it might be obsolete if we decide to replace Visiomatic with Aladin in PH6. To be evaluated.

A correction is needed for the Legacy DES Science Server, which is to remove this button, since in LEGACY we will only have the DES DR2 image. This functionality should remain a requirement for the new image viewing application using Aladin.

I will change the issue to be a Fix in the dri repository and change the milestone to PH3
