### ISSUE TITLE
Improve Userquery UI/UX

### ISSUE THREAD

**Issue by glaubervila** [linea-it/dri#1305]
- [ ] Melhorar o menu lateral de inputs, tirar as divisões por tipo, transformar em um único acordeon.
- [x] Remover as External Tables.
- [ ] Melhorar as toolbar e a posições dos botões, principalmente o botão de executar. 
- [ ] Melhorar a formatação da tabela de jobs, as cores devem ser só na coluna status.

**Comment by gschwend** [comment]
@glaubervila does this issue belong to the other repository (lsp_daiquiri)?

**Comment by glaubervila** [comment]
> @glaubervila does this issue belong to the other repository (lsp_daiquiri)?

This issue is invalid, it refers to the userquery application developed by LIneA that was discontinued and replaced by Daiquiri.
