### ISSUE TITLE
Add the name of the environment on the home page.

### ISSUE THREAD

**Issue by glaubervila** [linea-it/dri#1411]
Descrição atualizada: 

- [ ] Trocar o título da home de "LIneA Science Server"  para "LIneA Science Server @NCSA" onde o "@NCSA" é subscrito.
- [ ] Trocar o subtítulo de "DES Data Release" para um subtítulo que identifique se é o site público ou o da colaboração. Sugestões: 
    * Public Data Releases
    * Data Releases for the DES Collaboration Members  

 

Descrição original do issue: 

Sugerido pelo @adrianopieres no ticket [14067](https://ticket.linea.org.br/ticket/14067#no3)

> Como sugestão discutido agora na reunião de documentos seria colocar alguma
> indicação logo na página de acesso do desportal e desportal2 sobre se a
> página é pública ou com acesso restrito apenas para a colaboração.

**Comment by glaubervila** [comment]
Falta fazer o update dos ambientes.

**Comment by glaubervila** [comment]
Fiz o update do science server dev mas o tem um bug, voltei a versão.

**Comment by gschwend** [comment]
@glaubervila este seria um issue apropriado para delegar para o Jandson?
