### ISSUE TITLE
Error when changing view after clicking download

### ISSUE THREAD

**Issue by glaubervila** [linea-it/dri#1423]
Bug reportado  pelo @adrianopieres  no Ticket: https://ticket.linea.org.br/ticket/14176

Steps to reproduce:

> Acessa o skyviewer (DR2), clica no switch, clica em download (não precisa
> fazer o download, só clicar no botão) e depois tenta novamente clicar no
> switch que ele não faz nada.

**Comment by gschwend** [comment]
@glaubervila garantir que a correção seja aplicada em todas as instâncias: \

- [ ] @NCSA público
- [ ] @NCSA privad@glaubervila 
- [ ] science server @LIneA

**Comment by glaubervila** [comment]
Atualmente como só temos uma imagem, sugiro apenas ocultar o botão "Compare" já que não tem mais utilidade. 
dessa forma evitamos o bug de navegação e o problema do botão compare.
