### ISSUE TITLE
escrever documento explicando a como e o porque de usar stiffs para criar ptiffs

### ISSUE THREAD

**Issue by gschwend** [linea-it/dri#1429]
```[tasklist]
### Tasks
```

**Comment by adrianopieres** [comment]
O documento já foi escrito e compartilhado:
[https://docs.google.com/document/d/1RMHA8s0QpAAQ003BWTwMBKOnNEWPsRL36ZFhBtXFdl4/edit?usp=sharing](https://docs.google.com/document/d/1RMHA8s0QpAAQ003BWTwMBKOnNEWPsRL36ZFhBtXFdl4/edit?usp=sharing)
