### ISSUE TITLE
registrar resultados do JN numa lista integrada ao target viewer 

### ISSUE THREAD

**Issue by gschwend** [linea-it/dri#1431]
Avaliar a possibilidade de fazer com a biblioteca `dblinea`.

**Comment by glaubervila** [comment]
@gschwend Hoje já é possivel fazer o registro direto no Target Viewer usando  a opção database se a tabela existir no banco prod_gavo.  
Mas acredito que uma solução mais generica atenderia a dois requisitos o do JN e do Daiquiri. 
Acho que deveriamos permitir o registro de uma tabela no MY_DB do usuario que é criado pelo daiquiri. 
Essa seria uma forma de centralizar todas as tabelas do usuario no mesmo schema. 

Talvez o dblinea devesse ser só para leitura, e criação de tabela ficaria sob responsabilidade do daiquiri. 
Assim toda tabela criada pelo usuario faria parte do MY_DB_username.  facilita a nossa gestão e o registro  e utilização em qualquer ferrameta.

**Comment by glaubervila** [comment]
Foi implementado, no target viewer uma função que compara todas as tabelas do usuario no MYDB com os targets, caso exista uma tabela que foi registrada como target ela é registrada automaticamente. 
Ao entrar no target viewer o usuario terá mais uma folder chamada MYDB dentro dela a lista de tabelas que ele criou usando o userquery. 

Ao acessar a tabela pela primeira vez é solicitado a associação para idenficiar as colunas id, ra e dec.
