### ISSUE TITLE
melhorar página provisória

### ISSUE THREAD

**Issue by gschwend** [linea-it/dri#1439]
Melhorar a página provisória de produção do LIneA Science Server hospedada no LIneA. Endereço: [https://scienceserver.linea.org.br](https://scienceserver.linea.org.br)

- [x] Adotar identidade visual, mesmo sendo apenas uma página de aviso. Vide: https://pz-server.linea.org.br/ 
- [x] Melhorar texto e adicionar links para instâncias no NCSA: 

"This page is under development for a major upgrade. Please visit the current version of the platform hosted at NCSA at https://desportal.cosmology.illinois.edu/. If you need any help, [contact us](mailto:helpdesk@linea.org.br). "

**Comment by gschwend** [comment]
@carlosadean can you help @jandsonrj to find the resources used to make the PZ Server (production) temporary page online? 

This one:


![Image](https://github.com/linea-it/dri/assets/9534570/417610c3-c6d3-476e-a13d-38d1c46f8cfa)

**Comment by jandsonrj** [comment]
![image](https://github.com/linea-it/dri/assets/101944851/2a6b0916-7569-4c32-a310-1ef090a88de7)

**Comment by jandsonrj** [comment]
Task completed, @leandrops19  helped me throughout the procedure.
![image](https://github.com/linea-it/dri/assets/101944851/063e172f-7373-4beb-8ec2-b72b0e276b58)
