### ISSUE TITLE
Mover novas imagens do DES DR2 para o Lustre

### ISSUE THREAD

**Issue by carlosadean** [linea-it/dri#1441]
```[tasklist]
### Tasks
- [x] Hips
- [x] Ptif
- [x] Fits
```

**Comment by carlosadean** [comment]
@glaubervila @gschwend Os arquivos foram copiados do Lustre para o Archive e estão disponíveis em /archive/cl/public/des/dr2/images/hips.

OBS: os arquivos são os RGB gerados pelo @crisingulani

**Comment by glaubervila** [comment]
@carlosadean e @gschwend  Testei essa imagem no science server dev e não funcionou, acredito que seja falta de permissão nos arquivos. 
O arquivo existe no disco mas o Ngnix não exibe a imagem, lembro de nas outras tentativas ter sido necessário alterar a permissão do arquivos. 

Imagens de exemplo: 
https://scienceserver-dev.linea.org.br/data/releases/dr2/rgb/Norder3/Dir0/Npix572.png
https://scienceserver-dev.linea.org.br/data/releases/dr2/rgb/Norder5/Dir0/Npix4370.png
