### ISSUE TITLE
lib to get data from Comanage

### ISSUE THREAD

**Issue by gschwend** [linea-it/dri#1509]
Criar biblioteca separada para consulta dos dados do usuário do comanage + ldap que seja genérica e possa ser usada pelos diversos microsserviços.

**Comment by glaubervila** [comment]
Foi implementado uma classe que permite fazer está consulta, mas não é uma lib que pode ser compartilhada, 
Na forma como foi feita cada aplicação django precisa de sua propria cópia da classe.
