### ISSUE TITLE
Padronização da landing page

### ISSUE THREAD

**Issue by gschwend** [linea-it/dri#1515]
- [x] remover logo duplicado no header (manter o do footer)
- [x] botão para login levando para a nova página de login (não será mais  SIGN IN   SIGN UP) 
- [x] incluir o captcha para o email do contact
- [x] #1517
- [x] Título da página = "DES Science Server" 
- [x] subtítulo = Data Release 2
- [x] subsubtítulo = Development (remover quando for para produção) 
- [x] logo para para ao lado do título

**Comment by luiz-nicolaci** [comment]
incluir o catcha para o email do contact

**Comment by luiz-nicolaci** [comment]
maybe a link to the new documentation
