### ISSUE TITLE
incluir link para página docs.linea.org.br

### ISSUE THREAD

**Issue by gschwend** [linea-it/dri#1517]
Na página "ABOUT" tem essa frase: 

For more information see the tutorials.

Substituir por:

For more information see the [documentation](http://docs.linea.org.br) and [video tutorials](https://scienceserver-dev.linea.org.br/tutorials)

Repara que o link para a página de vídeo tutoriais na verdade deveria ser um link interno pra funcionar depois em produção.

**Comment by jandsonrj** [comment]
Task forwarded in PR #1536
