### ISSUE TITLE
Verificar nome tabela des_dr2

### ISSUE THREAD

**Issue by deborajanini** [linea-it/dri#1526]
@carlosadean @glaubervila a tabela que está disponível no daiquiri foi ingerida a partir dos arquivos do des_dr2_main? ou veio da antiga coadd_objects do y6? se veio da main, deve manter o nome com sufixo main, se veio da coadd, vamos precisar substituí-la.

**Comment by carlosadean** [comment]
@gschwend @adrianopieres 

Sobre este issue que trata de verificar o nome da tabela des_dr2, eu não encontrei nas notas de transferência nem na antiga planilha de data transfer o registro referente a essa transferência realizada na época pelo Valter.

Mas tenho algumas informações que talvez possam ajudar a identificar se a tabela é a main.

**Deixei em meu scratch dois arquivos:**
- `des_dr2.rd` que foi utilizado para ingerir os dados com o gavo
- `des_dr2.txt` que contém o path para os 10169 'arquivos main' que estão no `/archive`

Se com essas informações não conseguirmos validar então teremos que transferir novamente.

Precisa criar uma task para validar se os dados da tabela correspondem ao que está nos arquivos no `/archive`. Quem ficará responsável por realizar essa validação? @deborajanini
