### ISSUE TITLE
Atualizar paths para imagens no lustre

### ISSUE THREAD

**Issue by gschwend** [linea-it/dri#1530]
Paths novos na planilha sizing: aba Curadoria 

https://docs.google.com/spreadsheets/d/1FqtFvBoazHUNxREaK_pbLyJi3Ooymtg5DJ14CCMrNlM/edit?gid=932959168#gid=932959168

![Image](https://github.com/user-attachments/assets/6abe1f9b-d629-4d83-b94e-5b6d09ae9eb9)

![Image](https://github.com/user-attachments/assets/30ff4a4a-a57b-4bee-9d54-b46b90915aea)

**Comment by glaubervila** [comment]
Atualizei o banco de dados do ambiente -dev para refletir a nova estrutura de pastas.
Foi alterado a url da imagem HIPs do DR2 e as imagens PTIFs todas utilizando a raiz /lustre/t1/public/des/dr2/
No docker compose eu não monto o path inteiro somente o que é necessário para aplicação:

HIPS: /lustre/t1/public/des/dr2/secondary/images/coadd/hips_rgb:/var/www/data/releases/dr2/
PTIFS: /lustre/t1/public/des/dr2/primary/images/coadd/:/data/releases/dr2/coadd

Dessa forma no banco de dados as urls estão utilizando o path interno do container: `/data/releases/dr2/coadd`

**Comment by adrianopieres** [comment]
Eu acessei as imagens HIPS e, diferentemente do que acontecia lá no desportal e desportal2, não há problemas com os diferentes NORDERS, ou seja, as imagens HIPS aparecem em todos os níveis. As imagens PTIFs também apareceram para todos os tiles que eu acessei.
