### ISSUE TITLE
Validate DR2 IMAGES

### ISSUE THREAD

**Issue by deborajanini** [linea-it/dri#1531]
Inspecionar imagens do DES DR2 após atualização dos paths pelo Glauber:

https://github.com/linea-it/dri/issues/1530

**Comment by adrianopieres** [comment]
Creio que eu precise de um link para a validação das imagens. Alguém pode me passar esse link?

**Comment by gschwend** [comment]
@carlosadean essa lista de imagens faltantes já foram localizadas? quem poderia ajudar nisso?
