### ISSUE TITLE
Target Viewer + MYDB error in rating/reject tables.

### ISSUE THREAD

**Issue by glaubervila** [linea-it/dri#1538]
Após mudar o banco de dados do scienceserver para utilizar o mydb no prod_gavo, o target viewer parou de exibir o conteudo das tabelas. 

O problema é causado por um join em duas tabelas que atualmente não são mais utilizadas ( rating e reject ) que não existem no banco prod_gavo. 

**SOLUÇÃO** 
A forma mais simples de resolver o problema é não fazer esses 2 joins, no passado já tinha sido implementado uma solução para minimizar a dependencias dessas 2 tabelas. Agora como solução definitiva podemos não executar a query e retornar um resultado vazio, desta forma não impacta em nenhuma outra função que utiliza a query nos catalogos de target.

**Comment by gschwend** [comment]
@glaubervila movi esta para Done por engano, já corrigi trazendo de volta para In Progress.
