### ISSUE TITLE
Add standard footer similar to the institutional website

### ISSUE THREAD

**Issue by gschwend** [linea-it/dri#1553]

**Comment by gschwend** [comment]
@kirmairlima  FYI: criando agora pq esqueci de criar um para cada repositório. 
O footer padronizado será adicionado em todas as aplicações, 1 issue para cada.

**Comment by kirmairlima** [comment]
Oi,

Muito obrigado!

Abs,
Kirma

Em sex., 16 de ago. de 2024 às 12:40, Julia Gschwend <
***@***.***> escreveu:
