### ISSUE TITLE
erro de redirecionamento no endpoint saml2/metadata

### ISSUE THREAD

**Issue by carlosadean** [linea-it/dri#1567]
Tem um erro na URL de acesso aos metadados do science server, em ambas as instâncias. 

Ao que parece o django não está redirecionando, deve ser algum detalhe de configuração.
https://scienceserver.linea.org.br/saml2/metadata

Note que no pz-server-dev e no userquer-dev isso não ocorre.
https://pz-server-dev.linea.org.br/saml2/metadata
https://userquery-dev.linea.org.br/saml2/metadata

## homologação

Ao tentar acessar a url dos metadados SAML em, ocorre o erro abaixo.

![image](https://github.com/user-attachments/assets/882d4a5b-f4d7-46e7-a5e3-6d7fcadced25)

## produção

Em produção não é exibido erro, mas uma mensagem informando que a página não foi encontrada.

https://scienceserver.linea.org.br/saml2/metadata

**Comment by glaubervila** [comment]
@carlosadean adiciona uma / no final da url 

`https://scienceserver.linea.org.br/saml2/metadata/`
