### ISSUE TITLE
reativar email de notificação sobre novos registros

### ISSUE THREAD

**Issue by gschwend** [linea-it/dri#1581]
![Image](https://github.com/user-attachments/assets/68535dd6-ce88-4e98-97e2-f7715dd94acf)

**Comment by glaubervila** [comment]
Testado nos 2 ambientes -dev e production.

**Comment by gschwend** [comment]
Oi @glaubervila o @luiz-nicolaci reportou que o email diário não está funcionando desde 26/09. .
