### ISSUE TITLE
Create Validation app.

### ISSUE THREAD

**Issue by glaubervila** [linea-it/dri#9]
Create an app in Django that contains three APIs.
- Features (a list of possible defects found in a tile)
- Defects (association of a defect to a tile for a User.)
- Flagged (one tiles list marked as flagged.)

https://www.lucidchart.com/documents/edit/614c2407-2471-4d78-9a4e-ef5ca03c54e6?shared=true&

**Comment by alanot** [comment]
On this issue, I only created the app, since all the apis are contemplated on other issues.
